// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbyESM1G-hHHFWfALeT9H4VDbgAwFpFoA',
    appId: '1:740950846981:web:28fb6a35d8e962ecfaf66c',
    messagingSenderId: '740950846981',
    projectId: 'we-chat-82ad4',
    authDomain: 'we-chat-82ad4.firebaseapp.com',
    storageBucket: 'we-chat-82ad4.appspot.com',
    measurementId: 'G-DKRLDWD0CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-KHA2rys5X2V20fr7lKfwvupmMe1BfsI',
    appId: '1:740950846981:android:8ae0738919b52e6ffaf66c',
    messagingSenderId: '740950846981',
    projectId: 'we-chat-82ad4',
    storageBucket: 'we-chat-82ad4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbmcWcSlrtZrYUmYa6A1_-9DJe2RFK-KY',
    appId: '1:740950846981:ios:02968fd58564d152faf66c',
    messagingSenderId: '740950846981',
    projectId: 'we-chat-82ad4',
    storageBucket: 'we-chat-82ad4.appspot.com',
    iosClientId: '740950846981-et8r4d8ec2pcld4o1h946orc6r8aovo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
